---
attributes:
  users:
    bastion:
    - mrkn
    - nishimunea
    - yonashiro
    - katsuya
    - shimizu
    - iida
    - mitsuyoshi
    - hatappi
    - suthio
    - toshihiro
    - anochick
    - kawakubox
    - bino98
    - yamaura
    - kotaro
    - miyachik
    - takanamito
    - yhatt
    - morioka
    - ihara
    - yokoi
    - amano
    - yoshida
    - nishaya
    - tei
    - hashimoto
    - nishioka
    - nyamadori
    - anochick
